source "https://rubygems.org"

gem "rails", "2.3.17"
gem "simple-navigation", "3.7.0"
gem "i18n",  "0.4.2"
gem "json",  "1.6.1"
gem "chef",  "10.24.4"

gem "sprockets", "~> 2.0"

# Needed when running in production environment
gem "syslogger"
gem "kwalify"

group :assets do
  gem "sass",  "3.1.2"
  gem "haml",  "3.1.6"

  # Adds the Twitter bootstrap CSS and Javascript
  gem "bootstrap-sass", "2.1.1.0"

  # Since we're still on Rails 2, we need Compass for bootstrap-sass to work
  gem "compass-rails", "1.0.3"
end

group :development do
  # bundler requires these gems in development
  # gem "rails-footnotes"
end

group :test do
  # bundler requires these gems while running tests
  # gem "rspec"
  # gem "faker"
end

